/*
 * Customer Information Application
 * A set of RESTful API's that allow user to obtain all customer information, create a customer, update a customer, delete a customer
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sukantasinha2003@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Display Application Exception
 */
@Schema(description = "Display Application Exception")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-08-21T07:32:37.492Z[GMT]")
public class Error {
  @SerializedName("Exception Name")
  private String exceptionName = null;

  @SerializedName("Exception Description")
  private String exceptionDescription = null;

  public Error exceptionName(String exceptionName) {
    this.exceptionName = exceptionName;
    return this;
  }

   /**
   * Get exceptionName
   * @return exceptionName
  **/
  @Schema(example = "NumberFormatException", description = "")
  public String getExceptionName() {
    return exceptionName;
  }

  public void setExceptionName(String exceptionName) {
    this.exceptionName = exceptionName;
  }

  public Error exceptionDescription(String exceptionDescription) {
    this.exceptionDescription = exceptionDescription;
    return this;
  }

   /**
   * Get exceptionDescription
   * @return exceptionDescription
  **/
  @Schema(example = "This displays a NumberFormatException with a detailed message", description = "")
  public String getExceptionDescription() {
    return exceptionDescription;
  }

  public void setExceptionDescription(String exceptionDescription) {
    this.exceptionDescription = exceptionDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.exceptionName, error.exceptionName) &&
        Objects.equals(this.exceptionDescription, error.exceptionDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exceptionName, exceptionDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    exceptionName: ").append(toIndentedString(exceptionName)).append("\n");
    sb.append("    exceptionDescription: ").append(toIndentedString(exceptionDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
